services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4